name: PR review request

on:
  pull_request:
    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'matveii1' || github.event.requested_team.name == 'MrAlgoriZ'}}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const hasChangeLabel = currentLabels.some(label => label.name === 'Change');
            const hasConflictLabel = currentLabels.some(label => label.name === 'Conflict');
            const hasApprovedLabel = currentLabels.some(label => label.name === 'Approved');
            
            if (hasChangeLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'Change'
              });
            }
            if (hasConflictLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'Conflict'
              });
            }
            if (hasApprovedLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'Approved'
              });
            }
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['check']
            });
